In [2]:
import torch
import pandas as pd 
import sqlite3

In [4]:
conn = sqlite3.connect("app.db")

In [7]:
tabels = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", conn)
tabels

       name
0      user
1   session
2  problems

In [8]:
df_01 = pd.read_sql_query("SELECT *" \
                          "FROM user", conn)
df_01

,uid,name,email,password,privilege
0,2,master,master@gmail.com,$2b$12$l6mKrT2u8a6mQ4fXp2tHKufCi96F8oa/e6aCM2k...,admin

In [9]:
df_02 = pd.read_sql_query("SELECT *" \
                          "FROM session", conn)
df_02

   sid  uid                                        token
0    1    3  dzeUZOuXiuIBzay5XEL2gd9oKqjWpb3pc3afJyGZPIM

In [23]:
df_03 = pd.read_sql_query("SELECT *" \
                          "FROM problems", conn)
df_03.head()

,id,platform,external_id,title,slug,url,contest_id,problem_index,category,difficulty_raw,tags_raw,stats_raw,metadata_raw,first_seen_at,last_seen_at,last_fetched_at
0,1,CODEFORCES,2269:B,KiaKio and Squared Numbers,None,https://codeforces.com/problemset/problem/2269/B,2269,B,None,"{""rating"": 1000}","[""brute force"", ""implementation""]","{""solved_count"": 10422}","{""points"": 1000.0, ""problemset_name"": null}",2026-10-03 10:20:28.863393,2026-10-03 10:38:49.506973,2026-10-03 10:38:49.506973
1,2,CODEFORCES,2269:A,SauSaGe Bank,None,https://codeforces.com/problemset/problem/2269/A,2269,A,None,"{""rating"": 800}","[""greedy"", ""math""]","{""solved_count"": 15236}","{""points"": 500.0, ""problemset_name"": null}",2026-10-03 10:20:28.867326,2026-10-03 10:38:49.513474,2026-10-03 10:38:49.513474
2,3,CODEFORCES,2268:F,Deglado,None,https://codeforces.com/problemset/problem/2268/F,2268,F,None,"{""rating"": 3500}","[""constructive algorithms""]","{""solved_count"": 140}","{""points"": 3250.0, ""problemset_name"": null}",2026-10-03 10:20:28.869021,2026-10-03 10:38:49.515319,2026-10-03 10:38:49.515319
3,4,CODEFORCES,2268:E,Kia Kio and Tree of Life,None,https://codeforces.com/problemset/problem/2268/E,2268,E,None,"{""rating"": 2700}","[""data structures"", ""fft"", ""math"", ""trees""]","{""solved_count"": 287}","{""points"": 2750.0, ""problemset_name"": null}",2026-10-03 10:20:28.869665,2026-10-03 10:38:49.515939,2026-10-03 10:38:49.515939
4,5,CODEFORCES,2268:D,AghaBalaSar and Hamed,None,https://codeforces.com/problemset/problem/2268/D,2268,D,None,"{""rating"": 2600}","[""data structures"", ""dp"", ""trees""]","{""solved_count"": 524}","{""points"": 2250.0, ""problemset_name"": null}",2026-10-03 10:20:28.870136,2026-10-03 10:38:49.516646,2026-10-03 10:38:49.516646

In [22]:
sum = df_03.groupby("platform").size()
sum

platform
ATCODER        9625
CODEFORCES    11425
CSES            400
LEETCODE       4069
dtype: int64