In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("project_red_synthetic_sample.csv")
df.head()

,user_id,session,user_rating,last_problem_rating,last_problem_id,mean_solve_time_minutes,time_std_minutes,problems_solved,lower_bound,upper_bound,range_width,synthetic
0,SYN_00000,8,1578,1200.0,779:C,23.02,4.50,42,1280.0,1510.0,230.0,True
1,SYN_00000,9,1586,900.0,746:B,19.48,7.98,43,1020.0,1600.0,580.0,True
2,SYN_00000,10,1582,1100.0,638:A,21.24,7.95,44,920.0,1600.0,680.0,True
3,SYN_00000,11,1581,1100.0,NaN,21.24,7.95,44,1000.0,1800.0,800.0,True
4,SYN_00000,12,1571,1100.0,NaN,21.24,7.95,44,1000.0,1590.0,590.0,True

In [ ]:
df["synthetic"].unique()

array([ True])

In [5]:
df = pd.read_csv("project_red_center_width.csv")
df.head()

,user_id,last_problem_id,user_rating,last_problem_rating,mean_solve_time_minutes,time_std_minutes,problems_solved,center,width,lower_bound,upper_bound,synthetic
0,SYN_000000,2109:C3,2263.0,2600,31.77,4.34,64,2417.25,298.93,2267.78,2566.72,True
1,SYN_000001,606:B,1414.0,1600,31.28,9.94,84,1555.10,568.89,1270.65,1839.54,True
2,SYN_000002,913:D,1833.0,1800,29.39,11.96,79,1844.16,426.22,1631.05,2057.27,True
3,SYN_000003,1419:D2,1290.0,1500,41.23,17.98,142,1347.95,588.71,1053.59,1642.31,True
4,SYN_000004,1428:H,3385.0,3500,31.50,17.31,306,3396.72,226.51,3283.46,3509.97,True